server:
  port: 8888
spring:
  application:
    name: chryseis-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chryseis-financial/chryseis-config-repo
          search-paths: '{application}'
          clone-on-start: true
logging:
  level:
    org:
      springframework:
        cloud: debug
        web: debug

